### ISSUE TITLE
Business domain/logic discussion/design

### ISSUE THREAD

**Issue by jenac** [tnt-develop-team/tntserver#10]
- user information: user name, full, name, email ...
- tool information: name, description, size, weight, owner, ...
- sharing information: location, charge(fee), ...
- borrow request information: ...?

**Comment by xwowenzhao** [comment]
User
-email (id)
-password
-name
-address
-tool_owned
-tool_rented
-tool_requested

tool
-id
-name
-description
-model
-picture
-owned_by
-rented_by
-requested_by

request
-id 
-tool
-requested_by
-message_to_owner
-message_to_renter
-approved

**Comment by jenac** [comment]
Done
