### ISSUE TITLE
Ionic2 unit test framework research/spike

### ISSUE THREAD

**Issue by jenac** [tnt-develop-team/tntserver#11]
- research on JavaScript unit test framework
-- Jasmine is picked as our test framework for javascript
- create git branch and implement unit test
- document steps and share knowledge with the team

**Comment by it-rookie** [comment]
I will take this task.

**Comment by it-rookie** [comment]
Quora's choice: https://www.quora.com/What-is-the-most-popular-JavaScript-testing-framework-in-the-US

According to NPM (as of May 24, 2014):

    Mocha (515 dependents and 642k downloads)
    Chai (247 dependents and 276k downloads)
    nodeunit (118 dependents and 73k downloads)

Those are only for NodeJS based testing, however. If we expand the list to include front-end testing libs that aren't on NPM, and use github stars:

    Jasmine (6867)
    Mocha (4572)
    QUnit (2899)
    Nodeunit (1237)
    Chai (1136)

**Comment by jenac** [comment]
implemented, but looks not easy to debug
