### ISSUE TITLE
Spring REST docs Spike

### ISSUE THREAD

**Issue by jenac** [tnt-develop-team/tntserver#39]
Spike on how to use Spring REST docs.
Try apply the Spring REST docs on the existing Neo4J spike code.
Document/wiki and share with the team

**Comment by xwowenzhao** [comment]
If we apply HATEOAS, which makes restful API self-discoverale, to our restful API, we don't need documentation.

**Comment by jenac** [comment]
What is HATEOAS and how to apply it on SpringBoot?

**Comment by xwowenzhao** [comment]
What is HATEOAS?
HATEOAS, an abbreviation for Hypermedia As The Engine Of Application State, is a constraint of the REST application architecture. A REST client needs no prior knowledge about how to interact with any particular application or server beyond a generic understanding of hypermedia. The HATEOAS constraint decouples client and server in a way that allows the server functionality to evolve independently. 

By using HATEOAS, every API response will contain all URLs of resources at next lower level, so client can pick the one that it needs. 

How use it?
Include dependency of spring-hateoas, spring-data-rest-hal-browser (for debug). Use spring data rest.

More info?
http://projects.spring.io/spring-hateoas/

**Comment by jenac** [comment]
Could you create a spike branch and demo to us next meeting?

**Comment by xwowenzhao** [comment]
sure will do.

**Comment by jenac** [comment]
Good demo!
